sudo: false
language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
install:
  - composer install
script:
  - composer test
notifications:
  irc:
    channels:
      - "chat.freenode.net#countervandalism"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
