name: CI
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  php:
    strategy:
      matrix:
        include:
          # Has php5.6-8.0 and composer 2 pre-installed
          # https://github.com/actions/virtual-environments/blob/ubuntu16/20210531.0/images/linux/Ubuntu1604-README.md
          - os: ubuntu-16.04
            php: "5.6"
          # Has php7.1-8.0 and composer 2 pre-installed
          # https://github.com/actions/virtual-environments/blob/ubuntu18/20210531.0/images/linux/Ubuntu1804-README.md
          - os: ubuntu-18.04
            php: "7.2"
          - os: ubuntu-18.04
            php: "7.3"
          # Has php7.4-8.0 and composer 2 pre-installed
          # https://github.com/actions/virtual-environments/blob/ubuntu20/20210531.0/images/linux/Ubuntu2004-README.md
          - os: ubuntu-20.04
            php: "7.4"
          - os: ubuntu-20.04
            php: "8.0"
    # Use "PHP 0.0" as job name instead of "php (ubuntu-, 0.0)"
    name: PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use PHP ${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: composer install
        run: composer install

      - name: composer test
        run: composer test
