name: CI
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  php:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Has php7.4-8.2 and composer 2 pre-installed
          # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
          - os: ubuntu-20.04
            php: "7.4"

    # Use "PHP 0.0" as job name instead of "php (ubuntu-, 0.0)"
    name: PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use PHP ${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: composer install
        run: composer install

      - name: composer test
        run: composer test
        env:
          XDEBUG_MODE: coverage
